/**
 * Model Performance / About page
 *
 * Shows real metrics from the backend (/dashboard/model-performance endpoint).
 * Only displays metrics that are actually available — no fabricated numbers.
 */
import { useEffect, useState } from 'react';
import Layout from '@/components/Layout';
import { api } from '@/lib/api';
import { ErrorBanner } from '@/components/ui/ErrorState';
import { ConfidenceBar } from '@/components/ui/ConfidenceBar';
import { pct } from '@/lib/utils';
import {
  Microscope, Info, AlertTriangle, BarChart2,
  Activity, ShieldCheck, CheckCircle2,
} from 'lucide-react';

export default function ModelPerformancePage() {
  const [data,    setData]    = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState('');

  useEffect(() => {
    api.getModelPerformance()
      .then(setData)
      .catch(() => setError('Failed to load model performance data.'))
      .finally(() => setLoading(false));
  }, []);

  return (
    <Layout>
      <div className="max-w-4xl mx-auto space-y-6 animate-fade-up">

        {/* Header */}
        <div>
          <h1 className="page-title flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-teal-700 flex items-center justify-center">
              <Microscope className="w-4 h-4 text-white" />
            </div>
            Model Information
          </h1>
          <p className="page-sub">AI model architecture and operational metrics</p>
        </div>

        {error && <ErrorBanner message={error} />}

        {/* Model architecture */}
        <div className="card space-y-5">
          <h2 className="text-sm font-bold text-ink flex items-center gap-2">
            <Info className="w-4 h-4 text-teal-600" /> Model Architecture
          </h2>
          <div className="grid sm:grid-cols-2 gap-x-8 gap-y-4">
            {[
              { label: 'Architecture',      val: 'EfficientNet-B0' },
              { label: 'Classification',    val: '5-class (No DR → Proliferative DR)' },
              { label: 'Input resolution',  val: '224 × 224 px (RGB)' },
              { label: 'Normalisation',     val: 'ImageNet mean/std' },
              { label: 'Output activation', val: 'Softmax (class probabilities)' },
              { label: 'Explainability',    val: 'Grad-CAM (last conv layer)' },
            ].map(row => (
              <div key={row.label} className="flex flex-col gap-0.5">
                <p className="text-xs text-ink-subtle">{row.label}</p>
                <p className="text-sm font-semibold text-ink">{row.val}</p>
              </div>
            ))}
          </div>

          {/* Class labels */}
          <div>
            <p className="text-xs font-semibold text-ink-muted uppercase tracking-wide mb-3">
              Classification Classes
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
              {[
                { n: 0, label: 'No DR',           cls: 'sev-0' },
                { n: 1, label: 'Mild NPDR',        cls: 'sev-1' },
                { n: 2, label: 'Moderate NPDR',    cls: 'sev-2' },
                { n: 3, label: 'Severe NPDR',      cls: 'sev-3' },
                { n: 4, label: 'Proliferative DR', cls: 'sev-4' },
              ].map(c => (
                <div key={c.n} className="bg-surface-subtle rounded-xl p-3 text-center">
                  <span className={`badge ${c.cls} mb-1.5`}>Level {c.n}</span>
                  <p className="text-xs font-medium text-ink">{c.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Demo mode notice */}
        <div className="alert alert-warning">
          <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-sm">Demonstration Mode Active</p>
            <p className="text-xs mt-1 leading-relaxed">
              This system is running in <strong>DEMO MODE</strong>. Predictions are
              generated by a pixel-analysis heuristic (red lesion density, edge complexity,
              contrast) applied to the actual image. This is not a trained validated DR
              classifier. No validated performance metrics are available for this demo
              configuration. The EfficientNet-B0 architecture supports production use once
              trained on validated fundus image datasets (e.g. EyePACS / APTOS 2019).
            </p>
          </div>
        </div>

        {/* Operational metrics (real data from DB) */}
        {loading ? (
          <div className="skeleton h-48" />
        ) : data && (
          <>
            <div className="card space-y-5">
              <h2 className="text-sm font-bold text-ink flex items-center gap-2">
                <Activity className="w-4 h-4 text-teal-600" /> Operational Metrics
              </h2>
              <p className="text-xs text-ink-subtle">
                Based on screenings performed in this system. These are operational
                statistics, not clinical validation metrics.
              </p>

              <div className="grid sm:grid-cols-3 gap-4">
                {[
                  {
                    label: 'Average Confidence',
                    val: data.avg_confidence != null
                      ? `${(data.avg_confidence * 100).toFixed(1)}%` : '—',
                    icon: BarChart2,
                  },
                  {
                    label: 'AI–Clinician Agreement',
                    val: data.clinician_agreement_rate != null
                      ? `${data.clinician_agreement_rate}%` : '—',
                    icon: CheckCircle2,
                  },
                  {
                    label: 'Total Screenings Analysed',
                    val: data.total_screenings != null
                      ? data.total_screenings.toLocaleString() : '—',
                    icon: ShieldCheck,
                  },
                ].map(m => {
                  const Icon = m.icon;
                  return (
                    <div key={m.label} className="card-muted text-center p-4">
                      <div className="w-9 h-9 rounded-xl bg-teal-50 border border-teal-100
                                      flex items-center justify-center mx-auto mb-3">
                        <Icon className="w-4.5 h-4.5 text-teal-700" style={{ width:'18px', height:'18px' }} />
                      </div>
                      <p className="text-xl font-black text-ink">{m.val}</p>
                      <p className="text-xs text-ink-muted mt-1">{m.label}</p>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Confidence distribution */}
            {data.confidence_distribution && (
              <div className="card space-y-4">
                <h2 className="text-sm font-bold text-ink flex items-center gap-2">
                  <BarChart2 className="w-4 h-4 text-teal-600" /> Confidence Distribution
                </h2>
                <p className="text-xs text-ink-subtle">
                  Distribution of model confidence scores across all analysed screenings.
                </p>
                <div className="space-y-3">
                  {[
                    { label: 'High (≥ 80%)',   key: 'high',   colour: 'bg-emerald-400' },
                    { label: 'Medium (60–80%)', key: 'medium', colour: 'bg-amber-400' },
                    { label: 'Low (< 60%)',    key: 'low',    colour: 'bg-red-400' },
                  ].map(row => {
                    const val   = data.confidence_distribution?.[row.key] ?? 0;
                    const total = (data.confidence_distribution?.high ?? 0)
                                + (data.confidence_distribution?.medium ?? 0)
                                + (data.confidence_distribution?.low ?? 0);
                    const p = pct(val, total);
                    return (
                      <div key={row.key}>
                        <div className="flex justify-between text-xs mb-1.5">
                          <span className="font-medium text-ink">{row.label}</span>
                          <span className="text-ink-subtle">{val} screenings · {p}%</span>
                        </div>
                        <div className="progress-track">
                          <div className={`progress-fill ${row.colour}`} style={{ width: `${p}%` }} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </>
        )}

        {/* Evaluation notice */}
        <div className="card-muted p-5 space-y-2">
          <p className="text-sm font-semibold text-ink flex items-center gap-2">
            <Info className="w-4 h-4 text-teal-600" /> Evaluation Information
          </p>
          <p className="text-xs text-ink-muted leading-relaxed">
            Full clinical validation metrics (sensitivity, specificity, AUC, confusion matrix)
            require a validated ground-truth dataset and are not available in the current
            demonstration configuration. The EfficientNet-B0 architecture supports training
            on standard DR datasets (EyePACS, APTOS 2019, DDR). Once trained and validated,
            performance metrics should be reported per standard ophthalmology screening
            guidelines.
          </p>
          <p className="text-xs text-ink-muted leading-relaxed">
            <strong>No synthetic or estimated metrics are displayed.</strong> Only operational
            data collected from actual screenings performed in this system is shown above.
          </p>
        </div>

      </div>
    </Layout>
  );
}
