/**
 * MultiDiseaseResults — composite results section.
 *
 * Shows DR + Glaucoma + Cataract cards in a responsive grid,
 * followed by the RiskScoreBadge and risk factors list.
 *
 * Drop this anywhere a Screening object is available.
 */
import { Screening, SEVERITY_LABELS, GLAUCOMA_LABELS, CATARACT_LABELS } from '@/types';
import { DiseaseResultCard } from './DiseaseResultCard';
import { RiskScoreBadge }    from './RiskScoreBadge';
import { safeJson }          from '@/lib/utils';
import { Tag }               from 'lucide-react';

interface Props {
  screening: Screening;
}

export function MultiDiseaseResults({ screening }: Props) {
  const riskFactors: string[] = safeJson<string[]>(
    screening.risk_factors_present ?? null, []
  );

  return (
    <div className="space-y-5">

      {/* ── Disease result cards ─────────────────────────────────────────── */}
      <div>
        <p className="text-xs font-bold text-ink-muted uppercase tracking-wide mb-3">
          Disease Detection Results
        </p>
        <div className="grid sm:grid-cols-3 gap-4">

          <DiseaseResultCard
            disease="dr"
            severity={screening.predicted_severity}
            confidence={screening.prediction_confidence}
            label={
              screening.predicted_severity != null
                ? SEVERITY_LABELS[screening.predicted_severity]
                : null
            }
            message={undefined}
            requiresReview={screening.requires_human_review}
            maxSeverity={4}
            severityLabels={SEVERITY_LABELS}
          />

          <DiseaseResultCard
            disease="glaucoma"
            severity={screening.glaucoma_severity}
            confidence={screening.glaucoma_confidence}
            label={
              screening.glaucoma_severity != null
                ? GLAUCOMA_LABELS[screening.glaucoma_severity]
                : null
            }
            message={screening.glaucoma_message ?? undefined}
            requiresReview={screening.glaucoma_requires_review}
            maxSeverity={3}
            severityLabels={GLAUCOMA_LABELS}
          />

          <DiseaseResultCard
            disease="cataract"
            severity={screening.cataract_severity}
            confidence={screening.cataract_confidence}
            label={
              screening.cataract_severity != null
                ? CATARACT_LABELS[screening.cataract_severity]
                : null
            }
            message={screening.cataract_message ?? undefined}
            requiresReview={screening.cataract_requires_review}
            isPhase2={screening.cataract_is_phase2}
            maxSeverity={3}
            severityLabels={CATARACT_LABELS}
          />

        </div>
      </div>

      {/* ── Risk score ───────────────────────────────────────────────────── */}
      {screening.risk_score != null && screening.risk_category && (
        <RiskScoreBadge
          score={screening.risk_score}
          category={screening.risk_category}
          breakdownJson={screening.risk_breakdown}
          recommendation={screening.risk_recommendation}
        />
      )}

      {/* ── Risk factors ─────────────────────────────────────────────────── */}
      {riskFactors.length > 0 && (
        <div className="card">
          <p className="text-xs font-bold text-ink-muted uppercase tracking-wide mb-3 flex items-center gap-2">
            <Tag className="w-3.5 h-3.5 text-amber-500" />
            Risk Factors Identified
          </p>
          <div className="flex flex-wrap gap-2">
            {riskFactors.map((f, i) => (
              <span
                key={i}
                className="text-xs bg-amber-50 text-amber-700 border border-amber-200
                           px-2.5 py-1 rounded-full font-medium"
              >
                {f}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* ── AI disclaimer ─────────────────────────────────────────────────── */}
      <p className="text-[10px] text-ink-subtle px-1 leading-relaxed">
        <span className="font-semibold">Note:</span> All disease detections and risk scores are
        generated by AI heuristics (demo mode). They are for research and decision-support purposes
        only. Results must be validated by a qualified ophthalmologist before any clinical action.
        Glaucoma and Cataract detections are particularly experimental at this stage.
      </p>
    </div>
  );
}
